name: Check Runner OS

on: [push, pull_request]

jobs:
  check-runner-os:
    runs-on: self-hosted
    steps:
      - name: Print OS Info
        run: |
          echo "Running uname -a:"
          uname -a
      - name: Print Linux Distribution
        run: |
          echo "Checking distribution:"
          if [ -f /etc/os-release ]; then cat /etc/os-release; fi
          if [ -f /etc/lsb-release ]; then cat /etc/lsb-release; fi
